"""
Gaussian Filter Preprocessing Defense for Module 7 (Hardening).

Applies Gaussian spatial smoothing to input images before inference to attenuate
high-frequency adversarial perturbations.
"""

import time
from datetime import datetime
from typing import Any, Dict, List, Optional
import torch
import torch.nn as nn
import torch.nn.functional as F

from app.hardening.defenses.base import BaseDefense
from app.hardening.defenses.wrapper import HardenedModelWrapper
from app.hardening.hardening_result import HardeningMetadata, HardeningResult
from app.hardening.exceptions import DefenseExecutionError, HardeningConfigurationError


def apply_spatial_smoothing(
    inputs: torch.Tensor,
    kernel_size: int = 3,
    sigma: float = 1.0,
) -> torch.Tensor:
    """
    Apply Gaussian spatial smoothing filter to image tensors.

    Args:
        inputs: Input image tensor of shape (B, C, H, W).
        kernel_size: Size of Gaussian kernel (must be odd).
        sigma: Standard deviation of Gaussian distribution.

    Returns:
        torch.Tensor: Smooth preprocessed tensor of shape (B, C, H, W).
    """
    if inputs.ndim != 4:
        raise ValueError(
            f"Expected image tensor with shape (B, C, H, W), got {tuple(inputs.shape)}"
        )

    if kernel_size < 1 or kernel_size % 2 == 0:
        raise ValueError(
            f"kernel_size must be a positive odd integer, got {kernel_size}"
        )

    if sigma <= 0:
        raise ValueError(f"sigma must be positive, got {sigma}")

    channels = inputs.shape[1]
    # Create 1D Gaussian kernel
    x = torch.arange(kernel_size, dtype=torch.float32, device=inputs.device) - (kernel_size - 1) / 2.0
    kernel_1d = torch.exp(-0.5 * (x / sigma) ** 2)
    kernel_1d = kernel_1d / kernel_1d.sum()

    # Create 2D Gaussian kernel
    kernel_2d = torch.outer(kernel_1d, kernel_1d)
    # Expand kernel to match input channels: (C, 1, K, K)
    kernel = kernel_2d.view(1, 1, kernel_size, kernel_size).repeat(channels, 1, 1, 1)

    padding = kernel_size // 2
    smoothed = F.conv2d(inputs, kernel, padding=padding, groups=channels)
    return smoothed


class GaussianFilterDefense(BaseDefense):
    """
    Gaussian Filtering Defense.

    Applies 2D Gaussian blur to image tensors before model inference.
    Reduces high-frequency perturbations generated by gradient-based attacks (FGSM, PGD).
    """

    supported_domains: List[str] = ["image"]
    defense_family: str = "preprocessing"

    def __init__(
        self,
        kernel_size: int = 3,
        sigma: float = 1.0,
        name: str = "gaussian_filter",
        config: Optional[Dict[str, Any]] = None,
    ) -> None:
        """
        Initialize GaussianFilterDefense.

        Args:
            kernel_size: Odd integer kernel size (e.g. 3, 5).
            sigma: Standard deviation of Gaussian kernel.
            name: Defense registration identifier.
            config: Optional configuration dictionary.
        """
        cfg = config or {}
        defense_name = cfg.get("name", name)
        super().__init__(
            name=defense_name,
            defense_type="preprocessing",
            config=cfg,
            supported_domains=self.supported_domains,
            defense_family=self.defense_family,
        )
        self.kernel_size = int(cfg.get("kernel_size", kernel_size))
        self.sigma = float(cfg.get("sigma", sigma))

        if self.kernel_size % 2 == 0 or self.kernel_size < 1:
            raise HardeningConfigurationError(f"kernel_size must be a positive odd integer, got {self.kernel_size}")
        if self.sigma <= 0.0:
            raise HardeningConfigurationError(f"sigma must be positive, got {self.sigma}")

    def filter(self, inputs: torch.Tensor) -> torch.Tensor:
        """
        Apply Gaussian smoothing filter to inputs.
        """
        if not isinstance(inputs, torch.Tensor):
            raise HardeningConfigurationError(f"Expected torch.Tensor, got {type(inputs)}")
        if inputs.ndim != 4:
            return inputs.clone()
        return apply_spatial_smoothing(inputs, kernel_size=self.kernel_size, sigma=self.sigma)

    def apply(
        self,
        model: nn.Module,
        inputs: Optional[torch.Tensor] = None,
        labels: Optional[torch.Tensor] = None,
        **kwargs: Any,
    ) -> HardeningResult:
        start_time = time.time()
        try:
            hardened_inputs = self.filter(inputs) if inputs is not None else None
            self.mark_hardened_input(hardened_inputs, self.filter)
            wrapped_model = HardenedModelWrapper(model, self.filter, defense_name=self.name)

            exec_time = time.time() - start_time
            meta = HardeningMetadata(
                defense_name=self.name,
                defense_type=self.defense_type,
                parameters={"kernel_size": self.kernel_size, "sigma": self.sigma},
                execution_time_seconds=exec_time,
                timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                extra_metadata={"defense_family": self.defense_family},
            )
            return HardeningResult(
                hardened_model=wrapped_model,
                metadata=meta,
                hardened_inputs=hardened_inputs,
                success=True,
                recommendations=[
                    f"Applied Gaussian Filter defense (kernel_size={self.kernel_size}, sigma={self.sigma:.2f})."
                ],
            )
        except Exception as e:
            if isinstance(e, HardeningConfigurationError):
                raise
            raise DefenseExecutionError(f"GaussianFilterDefense failed: {str(e)}") from e


class SpatialSmoothingDefense(GaussianFilterDefense):
    """Backward-compatible subclass registered as 'spatial_smoothing'."""

    def __init__(
        self,
        kernel_size: int = 3,
        sigma: float = 1.0,
        config: Optional[Dict[str, Any]] = None,
    ) -> None:
        super().__init__(
            kernel_size=kernel_size,
            sigma=sigma,
            name="spatial_smoothing",
            config=config,
        )
